name: sagu
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- FIREBASE (Các phiên bản này tương thích chặt chẽ với nhau) ---
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_database: ^12.0.4

  # --- STATE MANAGEMENT & ROUTING ---
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0

  # --- UI & TIỆN ÍCH ---
  fl_chart: ^1.1.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true